CREATE TABLE regions
(
    region_id       NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 5
    PRIMARY KEY,
    region_name     VARCHAR2(50) NOT NULL   
);

/*
DROP TABLE regions; 
*/

CREATE TABLE countries
(
    country_id      CHAR(2)     PRIMARY KEY,
    country_name    VARCHAR(40) NOT NULL,
    region_id       NUMBER,
    
    CONSTRAINT fk_contries_regions FOREIGN KEY(region_id)
        REFERENCES regions(region_id)
        ON DELETE CASCADE
);

CREATE TABLE locations
(
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 24
        PRIMARY KEY,
    address     VARCHAR2(255) NOT NULL,
    postal_code VARCHAR2(20),
    city        VARCHAR2(50),
    state       VARCHAR2(50),
    country_id  CHAR(2),
    CONSTRAINT fk_locations_countries FOREIGN KEY(country_id)
        REFERENCES countries(country_id)
        ON DELETE CASCADE
);








